Repository glfw/glfw, pull requests merged in 2018-10, with the labels that each got.

#1339 Use memfd_create() and seals if available
  CMakeLists.txt
  src/glfw_config.h.in
  src/wl_window.c
Labels: Wayland

#1341 Add support for xdg-decoration
  .travis.yml
  CMakeLists.txt
  src/CMakeLists.txt
  src/wl_init.c
  src/wl_platform.h
  src/wl_window.c
Labels: Wayland, enhancement

#1344 Include the null byte in joystick path
  src/linux_joystick.c
Labels: Linux, bug

#1336 Remove the experimental Mir backend
  CMake/modules/FindMir.cmake
  CMakeLists.txt
  README.md
  deps/vulkan/vulkan.h
  docs/Doxyfile.in
  docs/compat.dox
  docs/compile.dox
  docs/news.dox
  docs/window.dox
  include/GLFW/glfw3native.h
  src/CMakeLists.txt
  src/egl_context.h
  src/glfw_config.h.in
  src/internal.h
  src/mir_init.c
  src/mir_monitor.c
  src/mir_platform.h
  src/mir_window.c
  src/vulkan.c
Labels: Mir

#1352 wayland: add support for XCURSOR_THEME and XCURSOR_SIZE
  src/wl_init.c
Labels: Wayland

#1328 Documentation work.
  docs/input.dox
Labels: documentation
